-- SQL to create the OTP codes table for custom Resend API integration
-- This table will store the 4-digit codes generated by the app

CREATE TABLE IF NOT EXISTS public.otp_codes (
    email TEXT PRIMARY KEY,
    code TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE DEFAULT (timezone('utc'::text, now()) + interval '10 minutes') NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.otp_codes ENABLE ROW LEVEL SECURITY;

-- Allow the frontend to manage OTP codes (Insert/Select/Delete)
-- Note: In a production environment, you would restrict this further,
-- but for a custom OTP flow to work from the browser, these are required.

DROP POLICY IF EXISTS "Enable insert for everyone" ON public.otp_codes;
CREATE POLICY "Enable insert for everyone" ON public.otp_codes 
    FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Enable read for everyone" ON public.otp_codes;
CREATE POLICY "Enable read for everyone" ON public.otp_codes 
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable update for everyone" ON public.otp_codes;
CREATE POLICY "Enable update for everyone" ON public.otp_codes 
    FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Enable delete for everyone" ON public.otp_codes;
CREATE POLICY "Enable delete for everyone" ON public.otp_codes 
    FOR DELETE USING (true);

-- Optional: Create a function to clean up expired codes automatically
-- This requires a cron job or manual cleanup, but for now, the table is ready.
